#!/usr/bin/env bash
# This script that pings an IP address passed as an argument.
if [ $# = 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    for arg in $@; do ping -c 5 "$arg"; done
fi
